<?php
namespace ResourceCatalog\Model;

interface IUserGroupIdentify
{
    const IDENTIFY = array(
        IUserGroup::ID['NULL'] => 'NULL',
        IUserGroup::ID['SFGW'] => 'SFGW',
        IUserGroup::ID['SJWJW'] => 'SJWJW',
        IUserGroup::ID['SWZZB'] => 'SWZZB',
        IUserGroup::ID['SXCB'] => 'SXCB',
        IUserGroup::ID['SZFB'] => 'SZFB',
        IUserGroup::ID['SRMYH'] => 'SRMYH',
        IUserGroup::ID['SSCJDGLJ'] => 'SSCJDGLJ',
        IUserGroup::ID['SSWJ'] => 'SSWJ',
        IUserGroup::ID['SRSJ'] => 'SRSJ',
        IUserGroup::ID['SHBJ'] => 'SHBJ',
        IUserGroup::ID['SFY'] => 'SFY',
        IUserGroup::ID['SJTJ'] => 'SJTJ',
        IUserGroup::ID['SWJ'] => 'SWJ',
        IUserGroup::ID['SMZWYH'] => 'SMZWYH',
        IUserGroup::ID['SJCY'] => 'SJCY',
        IUserGroup::ID['SYBJ'] => 'SYBJ',
        IUserGroup::ID['SGYHXXHJ'] => 'SGYHXXHJ',
        IUserGroup::ID['SYJGLJ'] => 'SYJGLJ',
        IUserGroup::ID['SZRZYJ'] => 'SZRZYJ',
        IUserGroup::ID['SGAJ'] => 'SGAJ',
        IUserGroup::ID['SJYJ'] => 'SJYJ',
        IUserGroup::ID['SJNHG'] => 'SJNHG',
        IUserGroup::ID['SYLJ'] => 'SYLJ',
        IUserGroup::ID['SWSJKW'] => 'SWSJKW',
        IUserGroup::ID['SJRB'] => 'SJRB',
        IUserGroup::ID['SNMJ'] => 'SNMJ',
        IUserGroup::ID['SZWFWJ'] => 'SZWFWJ',
        IUserGroup::ID['STJJ'] => 'STJJ',
        IUserGroup::ID['SKJJ'] => 'SKJJ',
        IUserGroup::ID['SMZJ'] => 'SMZJ',
        IUserGroup::ID['SSFJ'] => 'SSFJ',
        IUserGroup::ID['SSLJ'] => 'SSLJ',
        IUserGroup::ID['SZJJ'] => 'SZJJ',
        IUserGroup::ID['SZGH'] => 'SZGH',
        IUserGroup::ID['SWMB'] => 'SWMB',
        IUserGroup::ID['SCZJ'] => 'SCZJ',
        IUserGroup::ID['SGSL'] => 'SGSL',
        IUserGroup::ID['SWHTYJ'] => 'SWHTYJ',
        IUserGroup::ID['SLCJ'] => 'SLCJ',
        IUserGroup::ID['SGGZYJYZX'] => 'SGGZYJYZX',
        IUserGroup::ID['SYZGLJ'] => 'SYZGLJ',
        IUserGroup::ID['SXFJYZD'] => 'SXFJYZD',
        IUserGroup::ID['SSJJ'] => 'SSJJ',
        IUserGroup::ID['SGBDST'] => 'SGBDST',
        IUserGroup::ID['SRBS'] => 'SRBS',
        IUserGroup::ID['SCHEJJJSKFQ'] => 'SCHEJJJSKFQ',
        IUserGroup::ID['SWBB'] => 'SWBB',
        IUserGroup::ID['SGZW'] => 'SGZW',
        IUserGroup::ID['SYLBZJ'] => 'SYLBZJ',
        IUserGroup::ID['STW'] => 'STW',
        IUserGroup::ID['SFL'] => 'SFL',
        IUserGroup::ID['SYCJ'] => 'SYCJ',
        IUserGroup::ID['SWXB'] => 'SWXB',
    );
}
