<?php
namespace ResourceCatalog\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        'SFGW' => 1,
        'SJWJW' => 2,
        'SWZZB' => 3,
        'SXCB' => 4,
        'SZFB' => 5,
        'SRMYH' => 6,
        'SSCJDGLJ' => 7,
        'SSWJ' => 8,
        'SRSJ' => 9,
        'SHBJ' => 10,
        'SFY' => 11,
        'SJTJ' => 12,
        'SWJ' => 13,
        'SMZWYH' => 14,
        'SJCY' => 15,
        'SYBJ' => 16,
        'SGYHXXHJ' => 17,
        'SYJGLJ' => 18,
        'SZRZYJ' => 19,
        'SGAJ' => 20,
        'SJYJ' => 21,
        'SJNHG' => 22,
        'SYLJ' => 23,
        'SWSJKW' => 24,
        'SJRB' => 25,
        'SNMJ' => 26,
        'SZWFWJ' => 27,
        'STJJ' => 28,
        'SKJJ' => 29,
        'SMZJ' => 30,
        'SSFJ' => 31,
        'SSLJ' => 32,
        'SZJJ' => 33,
        'SZGH' => 34,
        'SWMB' => 35,
        'SCZJ' => 36,
        'SGSL' => 37,
        'SWHTYJ' => 38,
        'SLCJ' => 39,
        'SGGZYJYZX' => 40,
        'SYZGLJ' => 41,
        'SXFJYZD' => 42,
        'SSJJ' => 43,
        'SGBDST' => 44,
        'SRBS' => 45,
        'SCHEJJJSKFQ' => 46,
        'SWBB' => 47,
        'SGZW' => 48,
        'SYLBZJ' => 49,
        'STW' => 50,
        'SFL' => 51,
        'SYCJ' => 52,
        'SWXB' => 53
    );
}
